name: Build MSI

on:
  workflow_dispatch:

jobs:
  build-msi:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build MSI
        run: ./gradlew packageMsi

      - name: Upload unsigned MSI artifact
        id: upload-unsigned
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-msi
          path: '**/build/compose/binaries/main/msi/*.msi'

      - name: Submit signing request to SignPath
        uses: signpath/github-action-submit-signing-request@v1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: 'TODO-organization-id'
          project-slug: 'TODO-project-slug'
          signing-policy-slug: 'TODO-signing-policy-slug'
          artifact-configuration-slug: 'TODO-artifact-configuration-slug'
          github-artifact-id: '${{ steps.upload-unsigned.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: 'signed'

      - name: Upload signed MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-msi
          path: 'signed/*.msi'
